[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$environmentRoot = Join-Path $root "infra/terraform/environments/development"

function Read-TerraformFile([string]$Name) {
    $path = Join-Path $environmentRoot $Name
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Full Terraform architecture is missing $Name."
    }
    Get-Content -LiteralPath $path -Raw
}

$all = (Get-ChildItem -LiteralPath $environmentRoot -Filter *.tf | ForEach-Object {
    Get-Content -LiteralPath $_.FullName -Raw
}) -join "`n"
$network = Read-TerraformFile "network.tf"
$compute = Read-TerraformFile "compute.tf"
$frontend = Read-TerraformFile "frontend.tf"
$edge = Read-TerraformFile "edge.tf"
$cache = Read-TerraformFile "cache.tf"
$database = Read-TerraformFile "database.tf"
$queues = Read-TerraformFile "queues.tf"
$security = Read-TerraformFile "security.tf"
$pipeline = Read-TerraformFile "pipeline.tf"
$scheduling = Read-TerraformFile "scheduling.tf"
$providers = Read-TerraformFile "providers.tf"
$storage = Read-TerraformFile "storage.tf"
$runtime = Read-TerraformFile "runtime.tf"
$userData = Get-Content -LiteralPath (Join-Path $environmentRoot "templates/ec2-user-data.sh.tftpl") -Raw
$ciIdentity = (Get-ChildItem -LiteralPath (Join-Path $root "infra/terraform/ci-identity") -Filter *.tf | ForEach-Object {
    Get-Content -LiteralPath $_.FullName -Raw
}) -join "`n"
$artifactRoot = Join-Path $root "infra/terraform/artifact-foundation"
$artifactMain = Get-Content -LiteralPath (Join-Path $artifactRoot "main.tf") -Raw
$deployedVerifier = Get-Content -LiteralPath (Join-Path $root "scripts/verify-deployed-development.ps1") -Raw
if (($deployedVerifier | Select-String -Pattern 'Invoke-WebRequest[^\r\n]+-UseBasicParsing' -AllMatches).Matches.Count -ne 2) {
    throw "Deployed verification must support Windows PowerShell 5 without the retired Internet Explorer parser."
}

if (-not $deployedVerifier.Contains('& $terraform.Source "-chdir=$terraformDirectory" output -json')) {
    throw "The deployed verifier must pass Terraform's chdir option as one expanded native argument."
}
if (-not $deployedVerifier.Contains('CORE_RUNTIME_STABLE')) {
    throw "Deployed verification must inspect Core container health and restart stability through SSM."
}
foreach ($portableSsmBoundary in @(
    '$runtimeCheckScriptBase64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($runtimeCheckScript))',
    'base64 -d | bash',
    '[IO.File]::WriteAllText($runtimeParametersPath, $runtimeParameters, [Text.UTF8Encoding]::new($false))',
    'file://$runtimeParametersPath',
    'Remove-Item -LiteralPath $runtimeParametersPath -Force -ErrorAction SilentlyContinue'
)) {
    if (-not $deployedVerifier.Contains($portableSsmBoundary)) {
        throw "Deployed verification must pass multiline SSM parameters through a UTF-8 JSON file and clean it up on every host: $portableSsmBoundary"
    }
}
if ($deployedVerifier.Contains("'--parameters', `$runtimeParameters")) {
    throw "Deployed verification must not pass multiline SSM JSON inline because Windows PowerShell 5 splits it into AWS CLI options."
}

foreach ($forbidden in @(
    'resource "aws_nat_gateway"',
    'resource "aws_lb"',
    'resource "aws_instance" "batch"',
    'resource "aws_instance" "compute"',
    'm7i-flex',
    'x86_64',
    'amd64-server'
)) {
    if ($all.Contains($forbidden)) {
        throw "Low-cost Development architecture forbids: $forbidden"
    }
}

foreach ($required in @(
    'resource "aws_subnet" "public"',
    'resource "aws_subnet" "private_db"',
    'resource "aws_vpc_endpoint" "s3"'
)) {
    if (-not $network.Contains($required)) {
        throw "Network architecture is missing: $required"
    }
}
foreach ($identityKey in @(
    'IDENTITY_EMAIL_ENCRYPTION_KEY  = base64encode(random_password.identity_email_encryption[0].result)',
    'IDENTITY_LOOKUP_HMAC_KEY       = base64encode(random_password.identity_lookup_hmac[0].result)',
    'IDENTITY_VERIFICATION_HMAC_KEY = base64encode(random_password.identity_verification_hmac[0].result)',
    'IDENTITY_SESSION_HMAC_KEY      = base64encode(random_password.identity_session_hmac[0].result)'
)) {
    if (-not $runtime.Contains($identityKey)) {
        throw "Identity runtime keys must be stored as standard Base64 over their full generated byte material: $identityKey"
    }
}

foreach ($immutableFrontendBoundary in @(
    'count = local.enable_dns_foundation ? 1 : 0',
    'origin_path              = "/_releases/${var.frontend_release_id}"'
)) {
    if (-not $frontend.Contains($immutableFrontendBoundary)) {
        throw "Immutable frontend release boundary is missing: $immutableFrontendBoundary"
    }
}
foreach ($runtimeDependency in @(
    'aws_instance" "service',
    'aws_instance" "trading',
    'aws_launch_template" "backtest'
)) {
    if ($compute -notmatch ('(?s)resource "' + [regex]::Escape($runtimeDependency) + '.*?depends_on\s*=\s*\[.*?aws_ssm_parameter\.runtime_image')) {
        throw "Runtime bootstrap can race its image parameter: $runtimeDependency"
    }
}
foreach ($runtimeRefreshBoundary in @(
    'runtime_name="$(basename "$repository")"',
    '--name ''${parameter_path}/deployment/images/''"$runtime_name"',
    'docker compose --file "$refreshed_compose" config --quiet',
    'mv -f "$refreshed_compose" compose.yaml',
    'refresh_runtime_images'
)) {
    if (-not $userData.Contains($runtimeRefreshBoundary)) {
        throw "Runtime restart cannot refresh an immutable image pointer: $runtimeRefreshBoundary"
    }
}
if (-not $userData.Contains('mapfile -t runtime_images < <(docker compose --project-name idea2strategy config --images)') -or
    -not $userData.Contains('registry="$${runtime_images[0]%%/*}"')) {
    throw "Runtime startup must capture immutable images without a pipefail-sensitive head pipeline."
}
if ($userData.Contains('config --images | head -n1')) {
    throw "Runtime startup can fail with SIGPIPE when pipefail observes docker compose writing into head."
}
foreach ($coreHealthBoundary in @(
    'test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8080/actuator/health"]',
    'start_period: 180s',
    'timeout: 10s',
    'retries: 6'
)) {
    if (-not $userData.Contains($coreHealthBoundary)) {
        throw "Core health checks are too aggressive for the confirmed t4g.medium runtime: $coreHealthBoundary"
    }
}
if (($compute | Select-String -Pattern 'user_data_base64\s*=\s*base64gzip\(' -AllMatches).Matches.Count -ne 2 -or
    ($compute | Select-String -Pattern 'user_data\s*=\s*base64gzip\(' -AllMatches).Matches.Count -ne 1) {
    throw "Every EC2 bootstrap path must gzip user data before base64 encoding so the decoded payload stays within the 16,384-byte EC2 API limit."
}
if ($compute -match 'user_data\s*=\s*templatefile\(' -or
    $compute -match 'user_data\s*=\s*base64encode\(templatefile\(') {
    throw "Uncompressed EC2 bootstrap user data is forbidden."
}
if ($userData -match 'apt-get install[^\r\n]*\bawscli\b') {
    throw "Ubuntu 24.04 ARM64 does not provide an awscli apt candidate; bootstrap must use the pinned AWS CLI v2 ARM64 installer."
}
foreach ($awsCliBoundary in @(
    'awscli-exe-linux-aarch64-2.36.15.zip',
    '/tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli',
    'aws --version'
)) {
    if (-not $userData.Contains($awsCliBoundary)) {
        throw "Pinned AWS CLI v2 ARM64 bootstrap is missing: $awsCliBoundary"
    }
}
if (-not $userData.Contains('install -d -m 0755 /var/lib/idea2strategy')) {
    throw "Runtime artifact materialization requires its /var/lib/idea2strategy parent before mktemp creates atomic staging directories."
}
if ($userData.Contains('awslogs-stream-prefix')) {
    throw "The standalone EC2 Docker awslogs driver rejects the ECS-only awslogs-stream-prefix option."
}
foreach ($runtimeLogStream in @('backend-api', 'backend-worker', 'backtest-api', 'backtest-worker', 'market-gateway', 'trading-worker')) {
    if ($userData -notmatch ('awslogs-stream:\s*' + [regex]::Escape($runtimeLogStream))) {
        throw "EC2 Docker runtime log stream is missing: $runtimeLogStream"
    }
}
if ($userData.Contains('chmod -R go-w "$temporary"')) {
    throw "Atomic runtime artifact staging must not retain mktemp's root-only directory mode."
}
if (($userData | Select-String -Pattern 'find "\$temporary" -type d -exec chmod 0755' -AllMatches).Matches.Count -ne 2 -or
    ($userData | Select-String -Pattern 'find "\$temporary" -type f -exec chmod 0444' -AllMatches).Matches.Count -ne 2) {
    throw "Backtest and Trading materialization must publish traversable directories and immutable world-readable non-secret artifacts."
}
if (-not $userData.Contains('materialized_destination="/runtime/$runtime"') -or
    -not $userData.Contains('printf ''artifact.%s.local-path=%s/%s\n'' "$index" "$materialized_destination" "$relative_path"')) {
    throw "Trading receipts must bind artifact paths as seen inside the container, not host-only /var/lib paths."
}
foreach ($required in @(
    'resource "aws_ecr_repository" "runtime"',
    'image_tag_mutability = "IMMUTABLE"',
    'scan_on_push = true',
    'prevent_destroy = true'
)) {
    if (-not $artifactMain.Contains($required)) {
        throw "Isolated artifact foundation boundary is missing: $required"
    }
}
if ($storage.Contains('resource "aws_ecr_repository"')) {
    throw "The Development runtime state must not own ECR repositories; the isolated artifact foundation does."
}
if ($compute -notmatch '(?s)resource\s+"aws_launch_template"\s+"backtest".*?credit_specification\s*\{.*?cpu_credits\s*=\s*"standard"') {
    throw "Backtest t4g.medium must use standard CPU credits so saturation is visible without surplus-credit spend."
}
if ($database -notmatch '(?s)name\s*=\s*"rds\.force_ssl".*?apply_method\s*=\s*"pending-reboot"') {
    throw "The static rds.force_ssl parameter must use pending-reboot so an applied configuration converges without perpetual drift."
}
foreach ($required in @(
    'AWS_DEFAULT_REGION=${aws_region}',
    'BACKTEST_BASIC_QUEUE_URL',
    'BACKTEST_BASIC_DLQ_URL',
    'BACKTEST_BASIC_MAX_CONCURRENCY',
    'BACKTEST_BASIC_REQUEST_QUEUE_URL',
    'BACKTEST_BASIC_REQUEST_DLQ_URL',
    'BACKTEST_CUSTOM_QUEUE_URL',
    'BACKTEST_CUSTOM_DLQ_URL',
    'BACKTEST_CUSTOM_MAX_CONCURRENCY',
    'BACKTEST_COMPETITION_QUEUE_URL',
    'BACKTEST_COMPETITION_DLQ_URL',
    'BACKTEST_COMPETITION_MAX_CONCURRENCY',
    'BACKTEST_CUSTOM_REQUEST_QUEUE_URL',
    'BACKTEST_CUSTOM_REQUEST_DLQ_URL',
    'BACKTEST_COMPETITION_REQUEST_QUEUE_URL',
    'BACKTEST_COMPETITION_REQUEST_DLQ_URL',
    'BACKTEST_MAX_TOTAL_CONCURRENCY'
)) {
    if (-not $userData.Contains($required)) {
        throw "Backtest runtime environment injection is missing: $required"
    }
}
foreach ($tradingSecretBoundary in @(
    'refresh_trading_runtime_secrets() {',
    'grep -Ev ''^(AWS_DEFAULT_REGION|SPRING_DATASOURCE_USERNAME|SPRING_DATASOURCE_PASSWORD|ALPACA_API_KEY|ALPACA_API_SECRET)=''',
    'append_env_value "$refreshed_runtime_env" AWS_DEFAULT_REGION ''${aws_region}''',
    'append_json_field "$refreshed_runtime_env" ALPACA_API_SECRET "$alpaca_secret_key_secret" ALPACA_SECRET_KEY',
    'secret_json ''${trading_database_secret_arn}''',
    'secret_json ''${alpaca_api_key_secret_arn}''',
    'secret_json ''${alpaca_secret_key_secret_arn}'''
)) {
    if (-not $userData.Contains($tradingSecretBoundary)) {
        throw "Trading startup must refresh its stopped-instance credentials from Secrets Manager: $tradingSecretBoundary"
    }
}
if ($userData.IndexOf('refresh_trading_runtime_secrets') -gt $userData.IndexOf('refresh_runtime_images')) {
    throw "Trading secrets must be refreshed before immutable images and containers are started."
}

foreach ($required in @(
    'resource "aws_instance" "service"',
    'resource "aws_eip" "service"',
    'resource "aws_instance" "trading"',
    'resource "aws_launch_template" "backtest"',
    'resource "aws_autoscaling_group" "backtest"',
    'desired_capacity',
    'max_size',
    'http_put_response_hop_limit'
)) {
    if (-not $compute.Contains($required)) {
        throw "Compute architecture is missing: $required"
    }
}

if ($compute -notmatch '(?s)resource "aws_instance" "trading".*?lifecycle\s*\{.*?ignore_changes\s*=\s*\[\s*associate_public_ip_address\s*\]') {
    throw "Scheduled Trading instances must ignore the stopped-instance public-IP observation to avoid replacement drift."
}
if ($compute -notmatch 'desired_capacity\s*=\s*0' -or
    $compute -notmatch 'max_size\s*=\s*1' -or
    ($compute | Select-String -Pattern 'http_put_response_hop_limit\s*=\s*2' -AllMatches).Matches.Count -ne 3) {
    throw "Backtest must scale from zero to one and each Docker EC2 launch path must use IMDSv2 with container-compatible hop limit 2."
}
if ($compute -notmatch '(?s)resource\s+"aws_autoscaling_policy"\s+"backtest_start".*?adjustment_type\s*=\s*"ExactCapacity".*?scaling_adjustment\s*=\s*1.*?cooldown\s*=\s*0') {
    throw "Backtest queue wake-up must bypass scaling cooldown so an alarm can restore desired capacity immediately after idle scale-down."
}
if ($compute -notmatch '(?s)resource\s+"aws_cloudwatch_metric_alarm"\s+"backtest_request_queue_start".*?for_each\s*=\s*local\.backtest_request_lanes.*?metric_name\s*=\s*"ApproximateNumberOfMessagesVisible".*?alarm_actions\s*=\s*\[aws_autoscaling_policy\.backtest_start\[0\]\.arn\].*?QueueName\s*=\s*aws_sqs_queue\.backtest_request\[each\.key\]\.name') {
    throw "Every producer request queue must wake the desired-zero Backtest ASG before an intake worker exists."
}
if ($compute -notmatch '(?s)resource\s+"aws_launch_template"\s+"backtest"\s*\{\s*#checkov:skip=CKV_AWS_341:IMDSv2 tokens remain required; hop limit 2 is required for the non-root Docker worker to reach instance-profile credentials through the container network namespace\.') {
    throw "The backtest launch template must document the narrow CKV_AWS_341 exception for container-compatible instance-role access."
}

foreach ($size in @('c7g.xlarge', 't4g.medium')) {
    if ($all -notmatch ('default\s*=\s*"' + [regex]::Escape($size) + '"')) {
        throw "ARM64 sizing boundary is missing: $size"
    }
}
if ($all -match '(?s)variable\s+"service_instance_type"\s*\{.*?default\s*=\s*"t4g\.small"') {
    throw "Core must start on the approved t4g.medium boundary, not t4g.small."
}
if ($all -notmatch '(?s)variable\s+"monthly_budget_usd"\s*\{.*?default\s*=\s*180') {
    throw "The accepted Development monthly budget must default to USD 180."
}
foreach ($dnsBoundary in @(
    'enable_dns_foundation = contains(["dns_foundation", "host_ready", "full"], var.deployment_phase)',
    'local.enable_dns_foundation && var.existing_hosted_zone_id == ""',
    'variable "dns_delegation_verified"',
    'condition     = var.dns_delegation_verified'
)) {
    if (-not ($all.Contains($dnsBoundary) -or $edge.Contains($dnsBoundary))) {
        throw "Staged Route 53 delegation boundary is missing: $dnsBoundary"
    }
}
if ($all -notmatch 'contains\(\["market_data_bootstrap", "dns_foundation", "host_ready", "full"\], var\.deployment_phase\)') {
    throw "Development deployment phases must expose DNS-only and pre-DNS host-ready stages before the public runtime."
}

foreach ($required in @(
    'resource "aws_cloudfront_origin_access_control" "frontend"',
    'resource "aws_cloudfront_distribution" "frontend"',
    'resource "aws_s3_bucket_policy" "frontend_cloudfront"',
    'X-Idea2Strategy-Origin-Verify',
    'aws_eip.service[0].public_ip'
)) {
    if (-not ($frontend.Contains($required) -or $security.Contains($required))) {
        throw "CloudFront-to-Core boundary is missing: $required"
    }
}
if ($all -notmatch '(?s)resource\s+"aws_cloudwatch_metric_alarm"\s+"backtest_request_queue_oldest_message".*?for_each\s*=\s*local\.backtest_request_lanes.*?ApproximateAgeOfOldestMessage.*?aws_sqs_queue\.backtest_request\[each\.key\]\.name') {
    throw "Backtest producer request queue age monitoring is missing."
}
if ($all -notmatch '(?s)resource\s+"aws_cloudwatch_metric_alarm"\s+"backtest_request_dead_letter_visible".*?for_each\s*=\s*local\.backtest_request_lanes.*?ApproximateNumberOfMessagesVisible.*?aws_sqs_queue\.backtest_request_dlq\[each\.key\]\.name') {
    throw "Backtest producer request DLQ monitoring is missing."
}
if ($frontend -notmatch 'origin_protocol_policy\s*=\s*"https-only"') {
    throw "CloudFront must use HTTPS to the fixed Core origin."
}
if ($frontend -match 'custom_error_response') {
    throw "Distribution-wide custom error responses must not convert API 403/404 responses into SPA success pages."
}
foreach ($spaBoundary in @(
    'resource "aws_cloudfront_function" "spa_rewrite"',
    'event_type   = "viewer-request"',
    'function_arn = aws_cloudfront_function.spa_rewrite[0].arn',
    "request.uri = '/index.html'"
)) {
    if (-not $frontend.Contains($spaBoundary)) {
        throw "The frontend-only SPA rewrite boundary is missing: $spaBoundary"
    }
}
foreach ($required in @('certbot', '--dns-route53', 'secretsmanager get-secret-value', 'http_x_idea2strategy_origin_verify', 'proxy_pass http://127.0.0.1')) {
    if (-not $userData.Contains($required)) {
        throw "Core reverse-proxy bootstrap is missing: $required"
    }
}

if (-not $security.Contains('prefix_list_id') -or
    -not $security.Contains('cloudfront_origin') -or
    $security -match '(?s)ingress[^}]*cidr_ipv4\s*=\s*"0\.0\.0\.0/0"' -or
    $security -match '(?s)from_port\s*=\s*22') {
    throw "Core ingress must be CloudFront-prefix-list-only and SSH-free."
}

foreach ($required in @(
    'resource "aws_elasticache_serverless_cache" "this"',
    'resource "aws_elasticache_serverless_cache"'
)) {
    if (-not $cache.Contains($required)) {
        throw "Private Valkey Serverless architecture is missing: $required"
    }
}
if ($cache -notmatch 'engine\s*=\s*"valkey"') {
    throw "The serverless cache must use Valkey."
}

foreach ($lane in @('basic', 'custom', 'competition')) {
    if (-not $all.Contains($lane)) {
        throw "Backtest queue lane is missing: $lane"
    }
}
foreach ($required in @('resource "aws_sqs_queue" "backtest"', 'resource "aws_sqs_queue" "backtest_dlq"', 'redrive_policy', 'sqs_managed_sse_enabled')) {
    if (-not $queues.Contains($required)) {
        throw "Durable backtest queue safety is missing: $required"
    }
}
foreach ($required in @('resource "aws_sqs_queue" "backtest_request"', 'resource "aws_sqs_queue" "backtest_request_dlq"', 'resource "aws_sqs_queue_redrive_allow_policy" "backtest_request_dlq"')) {
    if (-not $queues.Contains($required)) {
        throw "Backtest request intake queue safety is missing: $required"
    }
}
foreach ($required in @('ALPACA_API_KEY', 'ALPACA_SECRET_KEY', 'alpaca-api-key-secret-arn', 'alpaca-secret-key-secret-arn')) {
    if (-not $all.Contains($required)) {
        throw "Alpaca secret reference boundary is missing: $required"
    }
}
foreach ($required in @(
    'aws_iam_openid_connect_provider',
    'token.actions.githubusercontent.com:aud',
    'token.actions.githubusercontent.com:sub',
    'github_repository_owner_id',
    'github_repository_id',
    'local.github_oidc_repository_subject',
    'environment:${var.github_plan_environment}',
    'environment:${var.github_environment}',
    'ReadOnlyAccess',
    'PowerUserAccess',
    'github_plan_role_arn',
    'PublishImmutableFrontendRelease',
    'ReadDeploymentPrerequisiteSecrets',
    'secretsmanager:GetSecretValue',
    '${local.name_prefix}/backtest/alpaca-secret',
    '${local.name_prefix}/database/pipeline-runtime',
    'TerraformStateObject',
    'iam:PassRole'
)) {
    if (-not $ciIdentity.Contains($required)) {
        throw "GitHub OIDC deployment boundary is missing: $required"
    }
}
if (-not $queues.Contains('resource "aws_ssm_parameter" "backtest_dlq_url"')) {
    throw "Each Backtest lane DLQ URL must be published for worker runtime injection."
}
if ($queues -notmatch 'value\s*=\s*each\.key\s*==\s*"basic"\s*\?\s*"2"\s*:\s*"1"') {
    throw "Backtest lane concurrency must be basic=2, custom=1, competition=1."
}
if ($queues -notmatch '(?s)resource\s+"aws_ssm_parameter"\s+"backtest_total_concurrency".*?value\s*=\s*"4"') {
    throw "Backtest total concurrency must allow all four lane slots on the single worker host."
}
foreach ($required in @(
    'resource "aws_cloudwatch_metric_alarm" "backtest_cpu_high"',
    'resource "aws_cloudwatch_metric_alarm" "backtest_cpu_credit_low"',
    'resource "aws_cloudwatch_metric_alarm" "backtest_memory_high"',
    'CPUCreditBalance',
    'AutoScalingGroupName'
)) {
    if (-not $all.Contains($required)) {
        throw "Backtest t4g.medium saturation monitoring is missing: $required"
    }
}
foreach ($runtimeRegionBoundary in @(
    'append_env_value "$runtime_secret_env" AWS_DEFAULT_REGION ''${aws_region}''',
    'append_env_value "$backtest_secret_env" AWS_DEFAULT_REGION ''${aws_region}''',
    'append_env_value "$batch_secret_env" AWS_DEFAULT_REGION ''${aws_region}'''
)) {
    if (-not $userData.Contains($runtimeRegionBoundary)) {
        throw "Every Core runtime that can call an AWS SDK must receive AWS_DEFAULT_REGION: $runtimeRegionBoundary"
    }
}
foreach ($pipelineBoundary in @(
    '{ name = "AWS_DEFAULT_REGION", value = var.aws_region }',
    '"s3:GetObjectVersion"',
    '"s3:DeleteObjectVersion"',
    'name = "PIPELINE_WORKER_FEATURE_OUTPUT"'
)) {
    if (-not $pipeline.Contains($pipelineBoundary)) {
        throw "Pipeline production feature output wiring is incomplete: $pipelineBoundary"
    }
}
if ($all -notmatch '(?s)data\s+"aws_iam_policy_document"\s+"service_queue_publish".*?aws_sqs_queue\.backtest\["basic"\]\.arn.*?aws_sqs_queue\.backtest_dlq\["basic"\]\.arn') {
    throw "Core backtest-api must be allowed to publish accepted Basic jobs and poison intake only to the Basic execution queue and its DLQ."
}
foreach ($observerBoundary in @(
    'RuntimeObserverHeartbeat',
    'RuntimeUnhealthyContainerCount',
    'RuntimeRestartDelta',
    'container_is_runtime_ready()',
    'if ! container_is_runtime_ready "$running" "$status" "$restarting" "$health"; then',
    'declare -A previous_container previous_restarts',
    'runtime_restart_delta()',
    'service_restart_delta="$(runtime_restart_delta "$container" "$restarts" "$previous_id" "$previous_count")"',
    'idea2strategy-runtime-health.timer',
    'resource "aws_cloudwatch_metric_alarm" "runtime_container_unhealthy"',
    'resource "aws_cloudwatch_metric_alarm" "core_runtime_heartbeat_missing"',
    'resource "aws_cloudwatch_metric_alarm" "core_status_check_failed"',
    'resource "aws_cloudwatch_metric_alarm" "pipeline_dead_letter_visible"'
)) {
    if (-not ($all.Contains($observerBoundary) -or $userData.Contains($observerBoundary))) {
        throw "Runtime crash-loop observability is incomplete: $observerBoundary"
    }
}

if (-not $deployedVerifier.Contains('container_is_runtime_ready()') -or
    -not $deployedVerifier.Contains('if ! container_is_runtime_ready "$running" "$status" "$restarting" "$health"; then') -or
    -not $deployedVerifier.Contains('declare -A initial_container initial_restarts') -or
    -not $deployedVerifier.Contains('test "$container" = "${initial_container[$service]}"') -or
    -not $deployedVerifier.Contains('test "$restarts" -eq "${initial_restarts[$service]}"')) {
    throw "The deployed verifier must accept a running worker without a Docker healthcheck while still enforcing declared healthchecks."
}
if ($deployedVerifier.Contains("docker inspect --format '{{.State.Health.Status}}'")) {
    throw "The deployed verifier must not dereference a missing Docker Health object."
}

$bashExecutable = $null
$gitBash = 'C:\Program Files\Git\bin\bash.exe'
if (Test-Path -LiteralPath $gitBash -PathType Leaf) {
    $bashExecutable = $gitBash
} else {
    $bashCommand = Get-Command bash -ErrorAction SilentlyContinue
    if ($null -ne $bashCommand) { $bashExecutable = $bashCommand.Source }
}
if ([string]::IsNullOrWhiteSpace($bashExecutable)) {
    throw "Bash is required to exercise the runtime health classification used on EC2."
}

function Invoke-BashProbe([string]$Script, [switch]$SyntaxOnly) {
    $encoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($Script))
    $mode = if ($SyntaxOnly) { '-n' } else { '' }
    & $bashExecutable -c "printf '%s' '$encoded' | base64 --decode | bash $mode"
    return $LASTEXITCODE
}

$observerScriptMatch = [regex]::Match(
    $userData,
    "(?ms)cat >/usr/local/sbin/idea2strategy-runtime-health <<'SCRIPT'\r?\n(?<script>.*?)\r?\nSCRIPT"
)
if (-not $observerScriptMatch.Success) {
    throw "Unable to extract the EC2 runtime observer for Bash syntax validation."
}
$observerScript = $observerScriptMatch.Groups['script'].Value `
    -replace '(?m)^%\{.*?\}\r?\n', '' `
    -replace '\$\$\{', '${'

$verifierScriptMatch = [regex]::Match(
    $deployedVerifier,
    "(?ms)\`$runtimeCheckScript = @'\r?\n(?<script>.*?)\r?\n'@"
)
if (-not $verifierScriptMatch.Success) {
    throw "Unable to extract the deployed runtime verifier for Bash syntax validation."
}

foreach ($script in @($observerScript, $verifierScriptMatch.Groups['script'].Value)) {
    $probeExitCode = Invoke-BashProbe -Script $script -SyntaxOnly
    if ($probeExitCode -ne 0) {
        throw "Runtime health Bash syntax validation failed with exit code $probeExitCode."
    }
}

foreach ($source in @($userData, $deployedVerifier)) {
    $matches = [regex]::Matches($source, '(?ms)^container_is_runtime_ready\(\) \{.*?^\}')
    if ($matches.Count -ne 1) {
        throw "Expected exactly one runtime health classification function in each runtime script."
    }
    $probe = $matches[0].Value + @'

set -eu
container_is_runtime_ready true running false missing
container_is_runtime_ready true running false healthy
if container_is_runtime_ready true running false starting; then exit 11; fi
if container_is_runtime_ready true running false unhealthy; then exit 12; fi
if container_is_runtime_ready false exited false missing; then exit 13; fi
if container_is_runtime_ready true restarting true missing; then exit 14; fi
if container_is_runtime_ready true running true missing; then exit 15; fi
'@
    $probeExitCode = Invoke-BashProbe -Script $probe
    if ($probeExitCode -ne 0) {
        throw "Runtime health classification truth table failed with exit code $probeExitCode."
    }
}

$restartDeltaMatches = [regex]::Matches($userData, '(?ms)^runtime_restart_delta\(\) \{.*?^\}')
if ($restartDeltaMatches.Count -ne 1) {
    throw "Expected exactly one per-service restart delta function in the EC2 observer."
}
$restartProbe = ($restartDeltaMatches[0].Value -replace '\$\$\{', '${') + @'

set -eu
test "$(runtime_restart_delta current 0 '' 0)" -eq 0
test "$(runtime_restart_delta current 0 missing 0)" -eq 0
test "$(runtime_restart_delta same 3 same 1)" -eq 2
test "$(runtime_restart_delta same 1 same 4)" -eq 1
test "$(runtime_restart_delta replacement 0 old 5)" -eq 1
test "$(runtime_restart_delta replacement 2 old 5)" -eq 3
'@
$probeExitCode = Invoke-BashProbe -Script $restartProbe
if ($probeExitCode -ne 0) {
    throw "Per-service restart delta truth table failed with exit code $probeExitCode."
}

if ($deployedVerifier.Contains('test "$stable_total" -eq "$restart_total"')) {
    throw "The deployed verifier must compare container identity and restart counts per service, not only an aggregate total."
}

foreach ($digestBoundary in @(
    '/idea2strategy/dev/deployment/images/$service',
    "docker inspect --format '{{.Config.Image}}'",
    'test "$configured_image" = "$expected_image"'
)) {
    if (-not $deployedVerifier.Contains($digestBoundary)) {
        throw "The deployed verifier must bind each Core container to its applied immutable digest: $digestBoundary"
    }
}

foreach ($required in @(
    'resource "aws_scheduler_schedule" "trading_start"',
    'resource "aws_scheduler_schedule" "trading_stop"',
    'America/New_York',
    'start',
    'stop'
)) {
    if (-not $scheduling.Contains($required)) {
        throw "Trading time-control boundary is missing: $required"
    }
}

foreach ($required in @(
    'resource "aws_ecs_cluster" "pipeline"',
    'resource "aws_ecs_cluster_capacity_providers" "pipeline"',
    'capacity_providers = ["FARGATE", "FARGATE_SPOT"]',
    'resource "aws_ecs_task_definition" "pipeline"',
    'capacity_provider_strategy',
    'FARGATE_SPOT',
    'cpu_architecture',
    'ARM64',
    'assign_public_ip'
)) {
    if (-not $pipeline.Contains($required)) {
        throw "Scale-to-zero ARM64 pipeline boundary is missing: $required"
    }
}
foreach ($required in @(
    'name = "pipeline-tmp"',
    'name                   = "pipeline-volume-init"',
    'user                   = "0:0"',
    'containerName = "pipeline-volume-init"',
    'condition     = "SUCCESS"',
    'sourceVolume  = "pipeline-tmp"',
    'containerPath = "/tmp"'
)) {
    if (-not $pipeline.Contains($required)) {
        throw "The non-root Fargate pipeline must initialize writable state and /tmp volumes before starting: $required"
    }
}
if ($pipeline -notmatch 'assign_public_ip\s*=\s*true') {
    throw "The desired-zero Fargate task needs public-IP egress because the design intentionally has no NAT gateway."
}

foreach ($required in @('allowed_account_ids', 'architecture', 'arm64')) {
    if (-not $providers.Contains($required)) {
        throw "Provider/AMI safety is missing: $required"
    }
}

Write-Output "Low-cost full Terraform architecture boundary checks passed."
